<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-24T15:32:33 IST" name="Default suite" finished-at="2023-12-24T15:32:40 IST" duration-ms="6750">
    <groups>
    </groups>
    <test started-at="2023-12-24T15:32:33 IST" name="Default test" finished-at="2023-12-24T15:32:40 IST" duration-ms="6750">
      <class name="com.medicare.Tests.LoginPageTest">
        <test-method is-config="true" signature="start_browser()[pri:0, instance:com.medicare.Tests.LoginPageTest@4d1c00d0]" started-at="2023-12-24T15:32:33 IST" name="start_browser" finished-at="2023-12-24T15:32:37 IST" duration-ms="4542" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start_browser -->
        <test-method signature="test_login()[pri:49, instance:com.medicare.Tests.LoginPageTest@4d1c00d0]" started-at="2023-12-24T15:32:37 IST" name="test_login" finished-at="2023-12-24T15:32:39 IST" duration-ms="1090" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_login -->
        <test-method signature="test_getTitle_page()[pri:50, instance:com.medicare.Tests.LoginPageTest@4d1c00d0]" started-at="2023-12-24T15:32:39 IST" name="test_getTitle_page" finished-at="2023-12-24T15:32:39 IST" duration-ms="73" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_getTitle_page -->
        <test-method signature="Test_validate_registration_Text()[pri:51, instance:com.medicare.Tests.LoginPageTest@4d1c00d0]" started-at="2023-12-24T15:32:39 IST" name="Test_validate_registration_Text" finished-at="2023-12-24T15:32:39 IST" duration-ms="355" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Hello Arpita !] but found [Hello user !]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Hello Arpita !] but found [Hello user !]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.medicare.Tests.LoginPageTest.Test_validate_registration_Text(LoginPageTest.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_validate_registration_Text -->
        <test-method signature="test_click_cart()[pri:52, instance:com.medicare.Tests.LoginPageTest@4d1c00d0]" started-at="2023-12-24T15:32:39 IST" name="test_click_cart" finished-at="2023-12-24T15:32:40 IST" duration-ms="570" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_click_cart -->
      </class> <!-- com.medicare.Tests.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
